spring:
  config:
    activate:
      on-profile: local

  jackson:
    serialization:
      INDENT_OUTPUT: false

#  datasource:
#    url: jdbc:h2:mem:contract
#    username: sa
#    password: 1
#    driver-class-name: org.h2.Driver

  datasource:
    url: jdbc:mysql://ec2-3-39-223-154.ap-northeast-2.compute.amazonaws.com/caremoa_contract
    username: user2
    password: user2
    driver-class-name: com.mysql.cj.jdbc.Driver



  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000
    open-in-view: false
  h2:
    console:
      enabled: true
      path: /h2-console

  # Kafka 설정
  cloud:
    function:
      #definition: wheneverClaimedThenCallContract;
      definition: consumer;producer
    stream:
      kafka:
        binder:
          #brokers: localhost:9091,localhost:9092,localhost:9093
          #zkNodes: localhost:2181,localhost:2182,localhost:2183
          brokers: ec2-3-39-223-154.ap-northeast-2.compute.amazonaws.com:9092
      bindings:
        producer-out-0:
          destination: caremoa-topic
          content-type: application/json
        consumer-in-0:
          destination: caremoa-topic
          content-type: application/json
#  kafka:
#    consumer:
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

#-------------------------------------------------------------
# Feign Client 호출 URL 정의
#-------------------------------------------------------------
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

prop:
  feign:
#    url: http://a4012beb6509f4d2e8bd8fb783d8229b-1946401046.ap-northeast-2.elb.amazonaws.com:8080/payment
    url: http://payment:8080/payment

server:
  port: 8080
  servlet:
    contextPath: /contract

# logging 설정
logging:
  config: classpath:logback/logback-${spring.profiles.active}.xml