spring:
  config:
    activate:
      on-profile: local
  messages:
    basename: messages/messages
    encoding: UTF-8

  datasource:
    url: jdbc:h2:tcp://localhost/~/contract
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000
    open-in-view: false

  # Kafka 설정
  cloud:
    function:
      #definition: wheneverClaimedThenCallContract;
      definition: consumer;producer
    stream:
      kafka:
        binder:
          #brokers: localhost:9091,localhost:9092,localhost:9093
          #zkNodes: localhost:2181,localhost:2182,localhost:2183
          brokers: localhost:9092
      bindings:
        producer-out-0:
          destination: contract
          content-type: application/json
        consumer-in-0:
          destination: contract
          content-type: application/json

server:
  port: 8080

# logging 설정
logging:
  config: classpath:logback/logback-${spring.profiles.active}.xml